#!/bin/sh

# For the benefit of emacs users: -*- shell-script -*-

exec --no-startup-id yabar -c $HOME/.config/yabar/yabar.conf

# Default modkey
set $mod Mod4

# Hide titlebar
#new_window pixel 2

# i3-gaps
gaps inner 4
gaps outer 4
smart_gaps on

default_border pixel 1
hide_edge_borders smart

# Use Mouse+$mod to drag floating windows to their wanted position
floating_modifier $mod

# Start a terminal
bindsym $mod+Return exec kitty

# Kill focused window
bindsym $mod+q kill

# Start rofi
bindsym $mod+d exec rofi -modi drun -show drun
bindsym $mod+space exec rofi -modi drun -show drun

# Move between windows
bindsym $mod+j focus left
bindsym $mod+k focus down
bindsym $mod+l focus up
bindsym $mod+semicolon focus right

# Alternatively, you can use the cursor keys:
bindsym $mod+Left focus left
bindsym $mod+Down focus down
bindsym $mod+Up focus up
bindsym $mod+Right focus right

# Move focused window
bindsym $mod+Shift+j move left
bindsym $mod+Shift+k move down
bindsym $mod+Shift+l move up
bindsym $mod+Shift+semicolon move right

# Alternatively, you can use the cursor keys:
bindsym $mod+Shift+Left move left 75 px
bindsym $mod+Shift+Down move down 75 px
bindsym $mod+Shift+Up move up 75 px
bindsym $mod+Shift+Right move right 75 px

# Split in horizontal orientation
bindsym $mod+h split h

# Split in vertical orientation
bindsym $mod+v split v

# Enter fullscreen mode for the focused container
bindsym $mod+f fullscreen toggle

# Change container layout (stacked, tabbed, toggle split)
bindsym $mod+s layout stacking
bindsym $mod+w layout tabbed
bindsym $mod+e layout toggle split

# Toggle tiling / floating
bindsym $mod+Shift+space floating toggle

# Change focus between tiling / floating windows
#bindsym $mod+space focus mode_toggle

# Focus the parent container
bindsym $mod+a focus parent

# Name the workspaces
# set $workspace1 "1   Home"
# set $workspace2 "1   Shell"
# set $workspace3 "3   Code"
# set $workspace4 "4   Web"
# set $workspace5 "5   Files"
# set $workspace6 "6  "
# set $workspace7 "7  "
# set $workspace8 "8  "
# set $workspace9 "9  "
# set $workspace0 "10  "

set $workspace1 "  Home "
set $workspace2 "  Shell "
set $workspace3 "  Code "
set $workspace4 "  Web "
set $workspace5 "  Files "
set $workspace6 "  Office"
set $workspace7 "  Creative"
set $workspace8 "  Communication"
set $workspace9 "  Music"
set $workspace0 "  "

# Switch to workspace
bindsym $mod+1 workspace $workspace1
bindsym $mod+2 workspace $workspace2
bindsym $mod+3 workspace $workspace3
bindsym $mod+4 workspace $workspace4
bindsym $mod+5 workspace $workspace5
bindsym $mod+6 workspace $workspace6
bindsym $mod+7 workspace $workspace7
bindsym $mod+8 workspace $workspace8
bindsym $mod+9 workspace $workspace9
bindsym $mod+0 workspace $workspace0

# Move focused container to workspace
bindsym $mod+Shift+1 move container to workspace $workspace1
bindsym $mod+Shift+2 move container to workspace $workspace2
bindsym $mod+Shift+3 move container to workspace $workspace3
bindsym $mod+Shift+4 move container to workspace $workspace4
bindsym $mod+Shift+5 move container to workspace $workspace5
bindsym $mod+Shift+6 move container to workspace $workspace6
bindsym $mod+Shift+7 move container to workspace $workspace7
bindsym $mod+Shift+8 move container to workspace $workspace8
bindsym $mod+Shift+9 move container to workspace $workspace9
bindsym $mod+Shift+0 move container to workspace $workspace0

## Always open some programs on specified workspace
#assign [class="firefox"] → $workspace2
#assign [class="Chromium"] → $workspace2
#assign [class="chromium"] → $workspace2
#assign [class="Google-chrome"] → $workspace2
#assign [class="google-chrome"] → $workspace2
#assign [class="TelegramDesktop"] → $workspace3
#assign [class="thunar"] → $workspace4
#assign [class="Thunar"] → $workspace4
#assign [class="subl"] → $workspace5
#assign [class="Subl"] → $workspace5
#assign [class="geany"] → $workspace5
#assign [class="Geany"] → $workspace5
#assign [class="Atom"] → $workspace5
#assign [class="atom"] → $workspace5
#assign [class="Gimp"] → $workspace6
#assign [class="VirtualBox"]    → $workspace8

# Enable float for some windows
for_window [class="Variety"] floating enable
for_window [class="Yad"] floating enable

# Reload the configuration file
bindsym $mod+Ctrl+c reload

# Restart i3 inplace (preserves your layout/session, can be used to upgrade i3)
bindsym $mod+Ctrl+r restart

# Lock screen
bindsym $mod+x exec power-menu

# Resize window (you can also use the mouse for that)
mode "resize"
{
    # Resize with the arrow keys
    bindsym Left resize shrink width 100 px or 100 ppt
    bindsym Down resize grow height 100 px or 100 ppt
    bindsym Up resize shrink height 100 px or 100 ppt
    bindsym Right resize grow width 100 px or 100 ppt

    # Back to normal: Enter or Escape
    bindsym Return mode "default"
    bindsym Escape mode "default"
}
bindsym $mod+r mode "resize"

# Defining colors
set $bg      #222222
set $fg      #ec0101
set $fgfoc	 #ffffff
set $fgnorm   #aaaaaa
set $cyan    #5beedc
set $gray    #696c6c
set $white   #ffffff

font pango:Monoid-Bold 13
for_window [class=".*"] title_format "<span size='smaller'>%title</span>"
title_align center
default_border pixel 2
focus_follows_mouse yes

# class                 bord. bg. text  ind.  child_border
client.focused          $fg   $bg $fgnorm   $bg   $fg
client.focused_inactive $gray $bg $gray $gray $gray
client.unfocused        $gray $bg $gray $gray $gray
client.urgent           $gray $bg $fg   $gray $gray
client.placeholder      $fg   $bg $fg   $gray $gray

# Start i3blocks to display a workspace bar
# bar
# {
#     position top
#     workspace_buttons yes
#     # tray_output       primary
#     #strip_workspace_numbers yes
#     separator_symbol ""
# 	  status_command i3blocks
# 	  font pango: Monoid-Retina 12
# 	  colors
# 	  {
#         #                    Border Background Text
# 		    focused_workspace   $fg    $fg    $fgfoc
# 		    active_workspace    $bg    $bg    $white
# 		    inactive_workspace  $bg    $bg    $fgnorm
# 		    urgent_workspace    $bg    $bg    $gray
# 		    background          $bg
#     }
# }

bar {
    position top
    workspace_buttons yes
    font pango: Monoid-Thin 12
    tray_output primary
    #separator_symbol "  "
    separator_symbol "     "
    status_command node ~/Development/node/njsI3bar/main.js
    colors
	  {
        #                    Border Background Text
		    focused_workspace   $fg    $fg    $fgfoc
		    active_workspace    $bg    $bg    $white
		    inactive_workspace  $bg    $bg    $fgnorm
		    urgent_workspace    $bg    $bg    $gray
		    background          $bg
    }
}


# Volume
bindsym XF86AudioRaiseVolume exec --no-startup-id "amixer set Master 5%+ unmute && pkill -RTMIN+2 i3blocks"
bindsym XF86AudioLowerVolume exec --no-startup-id "amixer set Master 5%- unmute && pkill -RTMIN+2 i3blocks"
bindsym XF86AudioMute exec --no-startup-id "amixer -q set Master toggle && pkill -RTMIN+2 i3blocks"
bindsym Mod1+Ctrl+l exec --no-startup-id "betterlockscreen -l dim"
bindsym Print exec --no-startup-id "h-screenshot"

# Luizinho's configuration
bindsym $mod+b exec google-chrome-stable; workspace $workspace4
bindsym $mod+t exec kitty; workspace $workspace2
bindsym $mod+c exec rofi -show
bindsym $mod+Shift+t exec thunar
for_window [class="Lxappearance"] floating enable sticky enable border normal
for_window [class="Nm-connection-editor"] floating enable sticky enable border normal
for_window [class="Gnome-font-viewer"] floating enable sticky enable border normal
for_window [class="UnityHub"] floating enable sticky enable border normal
for_window [class="MYKI"] floating enable sticky enable border normal
#for_window [class="zoom"] floating enable sticky enable border normal
for_window [class="Pavucontrol"] floating enable sticky enable border normal
for_window [class="Blueberry.py"] floating enable sticky enable border pixel 1
for_window [class="Xdg-desktop-portal-gtk"] floating enable sticky enable border pixel 1
for_window [class="Nitrogen"] floating enable sticky enable border pixel 1
#exec_always --no-startup-id xlay --dpi 192
bindsym $mod+Shift+minus move scratchpad
# Shows the first scratchpad window
bindsym $mod+minus scratchpad show
# Show the sup-mail scratchpad window, if any.
#bindsym mod4+s [title="^Sup ::"] scratchpad show
assign [class="kitty"] $workspace2
assign [class="Code"] $workspace3
assign [class="notion-nativefier-b11061"] $workspace7
assign [class="whatsapp-nativefier-d40211"] $workspace8
assign [class="Spotify"] $workspace9
assign [class="zoom"] $workspace8
for_window [urgent=latest] focus
exec --no-startup-id xss-lock --transfer-sleep-lock -- i3lock --nofork
bindsym $mod+Tab workspace back_and_forth
bindsym $mod+Shift+e exec "i3-nagbar -t warning -m 'Exit i3?' -B 'Yes, exit i3' 'i3-msg exit'"

# Startup prograbs
exec_always --no-startup-id autotiling
exec_always --no-startup-id "sh ~/.config/i3/startup.sh"
# exec-always --no-startup-id /home/luizinho/.config/polybar/launch.sh